name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: bahmutov/npm-install@v1
      env:
        CYPRESS_INSTALL_BINARY: 0
      with:
        working-directory: ./frontend
    - name: Tests
      working-directory: ./frontend
      run: npm run test
    - name: Build App
      working-directory: ./frontend
      run: npm run build
    - name: Build Storybook
      working-directory: ./frontend
      run: npm run build-storybook -- --loglevel warn
