name: Cypress Tests

on:
  push:
    branches: [master, dev]

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 14.x
        uses: actions/setup-node@master
        with:
          version: 14.x

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          build: npm run build
          start: npm start
